### PR TITLE
Enable native compilation with libgccjit-10-dev

### PR DESCRIPTION
**Pull request by tats**
This pull request is currently "draft" for testing purpose.

The native compilation feature seems still in development and
not yet enabled by default.

### CODE REVIEW

**Comment by dkogan** [comment]
Hi.

Thank you very much for this patch. I tried it out just now. The build
completes, and the resulting packages appear to be working, although I
haven't done any thorough testing.

The results are in the APT repo, so if you grab the latest packages, you
should have a native-comp-enabled emacs. If you try it out, let me know
how it goes.

Thanks!

**Comment by tats** [comment]
With my testing, almost works, but some historical/non-lexical-binding packages,
such as Mew and MHC, failed with the .eln files under ~/.emacs.d/eln-cache.
It seems compatibility problems with the native compilation.

Anyway, thanks for merging.

**Comment by dkogan** [comment]
Tatsuya Kinoshita ***@***.***> writes:

> With my testing, almost works, but some historical/non-lexical-binding
> packages, such as Mew and MHC, failed with the .eln files under
> ~/.emacs.d/eln-cache. It seems compatibility problems with the native
> compilation.

If that's the biggest thing that breaks, it's probably a reasonable
trade-off. I'll move to using this in my day-to-day in a week or two
probably.

I'll make a note about this update on the web page.

Thanks a lot for the patch!

**Comment by tats** [comment]
FYI,

To suppress many warnings when async native compiling, I added
`(setq comp-async-report-warnings-errors nil)` to the init file.

To avoid .eln compatibility problem, I added `-*- no-native-compile: t;-*-`
to the .el file, and removed the .eln file from ~/.emacs.d/eln-cache/28.0.50-*.

**Comment by tats** [comment]
> `(setq comp-async-report-warnings-errors nil)`

Recently, renamed to `native-comp-async-report-warnings-errors`.

**Pull request closed without merging**
